swagger: "2.0"
info: 
  title: hessssoloppppppp
  description: building and sensor
  contact:
    name: jinghuan wang
    email: jinghuan.wang@tuni.fi
  version: 1.0.0
servers:
  -url: "http://localhost:4000/"
  description: This is my local servers
  -url: "http://company.com/"
  decription: This is my compnat server
schemes:
  - "http"
  - "https"
paths:
  /buildings:
    description: Bulding info
    get:
      description: Operation to fetch buildings
      parameters:
        - in: query
          name: buildingname
          required: true
          schema: 
            type: string
            example: aaaaaa
      responses:
        200:
          description: Sucess Response
          content: 
            application/json:
              schema:
                type: array
                items:
                  properties:
                    buildingId: 
                      type: integer
                      example: 3
                    buildingName: 
                      type: string
                      example: ROSE
                    buildingAddress:
                      type: object
                      properties:
                        streetAdress: 
                          type: string
                        PostNumber:
                          type: integer
                    
        
  

  