swagger: "2.0"
info: 
  title: hessssoloppppppp
  description: building and sensor
  contact:
    name: jinghuan wang
    email: jinghuan.wang@tuni.fi
  version: 1.0.0
servers:
  -url: "http://localhost:4000/"
  description: This is my local servers
  -url: "http://company.com/"
  decription: This is my compnat server
schemes:
  - "http"
  - "https"


#/buildings
paths:
  /buildings:
    description: Bulding info

    #GET
    get:
      summary: Returns all buildings
      responses:
        200:
          description: Sucess Response
          content: 
            application/json:
              schema:
                type: array
                items:
                  properties:
                    buildingId: 
                      type: integer
                      example: 3
                    buildingName: 
                      type: string
                      example: ROSE
                    buildingAddress:
                      type: object
                      properties:
                        streetAdress: 
                          type: string
                        PostNumber:
                          type: integer
        401:
          description: authorization error
        400:
          description: hi, this is a bad request
        

    #POST
    post:
        summary: Add a new building
        parameters:
          
          - in: query
            name: building object
            required: true
            schema: 
              type: object
              example: 
        responses:
          201:
            description: Sucess Added
          401:
            description: authorization error


#/buildings/buildingID
  /buildings/2:
    description: One building info

    #GET
    get:
      summary: Return one building
      responses:
        200:
          description: Sucess Response
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: object
                    properties:
                      address:
                        type: string
                      PostNumber:
                        type: integer
                # example: {
                #     id: 3,
                #     name: aa,
                #     address:{StreetAddress: apple, PostNumber: 566}
                  # }
        401:
          description: authorization error

    #PATCH
    patch:
      summary: Update one building
      parameters:
        - in: query
          name: buildingID
          required: true
          schema:
            type: integer
            example: 5
      responses:
        204:
          description: Sucess updated
          content:
            application/json:
              schema:
                type: object
                example: {
                  id: 6,
                  name: Rakannus 8,
                  address: {Street address: apple, PostNumber: 356}
                }
        401:
          description: authorization error
        


#Sensor
  /buldings/buildingID/sensors:
      description: all sensors of a specific building
      get:
        summary: Returns all sensor of a building
        parameters:
          - in: query
            name: buildingID
            required: true
            schema: 
              type: integer
              example: 3
        responses:
          200:
            description: Sucess Response
            content: 
              application/json:
                schema:
                  type: array
                  items:
                    properties:
                      buildingId: 
                        type: integer
                        example: 3
                      buildingName: 
                        type: string
                        example: ROSE
                      buildingAddress:
                        type: object
                        properties:
                          streetAdress: 
                            type: string
                          PostNumber:
                            type: integer
          401:
            description: authorization error
          
      



          
    

    